graphql/foundation.graphql.org

data/members.yaml
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Remove test logo

content/projects.md
=> Update stale links

data/faq.yaml
Minor update to FAQ page with contact aliases, and correcting URLs for
membership info.
=> Update the FAQ file with contact information

content/members.md, content/projects.md, data/nav.yaml
https://landscape.graphql.org
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add landscape to nav

data/nav.yaml
Closes #9
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add contact link

content/contact.md, data/nav.yaml
=> Add a contact page

content/news/2019-10-27-GraphQL_Foundation_Launches_Interactive_Landscape.md
Add the news item for the launch of the landscape, and the new members
announcement.
=> Add news item for landscape and new members

content/news/2019-10-31-Linux Foundation Training Announces a Free Online Course-Exploring GraphQL.md
Adding the press release, which went over the wire today.
=> Add press release for edX course

layouts/_default/join.html
This change updates the specification membership agreement link to a form which
can be extended, should other specifications be created.
=> Update Specification Membership Agreement link

content/news/2020-04-02-GraphQL-Annual-Report-2019.md
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add blog post for GraphQL Foundation Annual Report

content/news/how-and-why-playground-and-graphiql-are-joining-forces.md
Adding a blog post on Playground and GraphiQL on behalf of Rikki.
=> Add blog post on playground and GraphiQL

content/news/2020-04-02-GraphQL-Annual-Report-2019.md
=> Minor tweak to formatting

content/news/graphiql-graphql-playground.md
this would improve the flow. thanks!
=> chore: add discord channel to the call for contribs

content/reports/annual-report-2019.md
=> Add an alias and fix a bad double quote

content/news/season-of-docs.md
This PR adds the blog post announcement of GraphQL joining the Season of docs program so that we can get more engagements and possibly more applications.
=> Added announcement about GraphQL and Season of Doc

content/news/newsletter-aug-2020.md, content/news/newsletter-august-2020.md
I translated [Eli's post on the GraphQL newsletter](https://docs.google.com/document/d/14ZwpLnIuiSnHfD0zSb2gLoC30MirG1LHlpcF3LFsPFM/edit?ts=5f46a3be#) to markdown for publishing on Sep 11, 2020.
=> added Eli's post

config.toml, content/news/graphql-newsletter/_index.md, content/news/newsletter-august-2020.md, content/news/newsletter-september-2020.md, data/nav.yaml, layouts/_default/section.html, layouts/partials/news-item/hero.html
This PR adds a new "newsletter" type, and the September newsletter.
cc/ @mayaptos
=> Add newsletter section and sep

content/news/newsletter-october-2020.md
=> Add October newsletter

content/join.md
=> Update error in membership tiers

content/join.md
=> Update membership levels

content/news/defer-stream.md
Adding a blog post about defer and stream to get feedback on experimental releases.
=> add defer/stream blog post

content/reports/annual-report-2019.md
=> Spelling fix

content/join.md
=> Update links and description for spec membership

content/news/newsletter-february-2021.md
=> Add February newsletter

content/news/newsletter-april-2021.md
=> Add April newsletter

content/news/newsletter-march-2021.md
=> Fix newsletter dates
